logging.py----logging---2024-09-08 22:04:16,714---INFO---try_exception---__main__---division by zero failed
