ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 19:43:20,181---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---Initializing  data ingestion pipeline steps
data_ingestion.py----data_ingestion---2024-09-11 19:43:20,181---INFO---ingest_data---Hate_classification.LOGGERS.logging---initialized Reading CSV from { self.path} 
data_ingestion.py----data_ingestion---2024-09-11 19:43:20,181---INFO---ingest_data---Hate_classification.LOGGERS.logging---initialized Reading CSV from { self.path} 
ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 19:43:20,236---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---successfully finished data ingestion pipeline steps
ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 19:43:20,236---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---successfully finished data ingestion pipeline steps
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,276---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,276---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,276---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing.py----data_processing---2024-09-11 19:43:20,276---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 19:43:20,276---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 19:43:20,276---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 19:43:20,276---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 19:43:20,278---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 19:43:20,278---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 19:43:20,278---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 19:43:20,278---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 19:43:20,280---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 19:43:20,280---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 19:43:20,280---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 19:43:20,280---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,290---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,290---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,290---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,290---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing.py----data_processing---2024-09-11 19:43:20,305---INFO---lower_case---Hate_classification.LOGGERS.logging---error applying the lowercase transformation - Error: "None of [Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,\n       ...\n       25286, 25287, 25288, 25289, 25290, 25291, 25292, 25294, 25295, 25296],\n      dtype='int64', length=24783)] are in the [columns]" has occurred in module: KeyError, line: 64, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,305---INFO---lower_case---Hate_classification.LOGGERS.logging---error applying the lowercase transformation - Error: "None of [Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,\n       ...\n       25286, 25287, 25288, 25289, 25290, 25291, 25292, 25294, 25295, 25296],\n      dtype='int64', length=24783)] are in the [columns]" has occurred in module: KeyError, line: 64, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,305---INFO---lower_case---Hate_classification.LOGGERS.logging---error applying the lowercase transformation - Error: "None of [Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,\n       ...\n       25286, 25287, 25288, 25289, 25290, 25291, 25292, 25294, 25295, 25296],\n      dtype='int64', length=24783)] are in the [columns]" has occurred in module: KeyError, line: 64, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,305---INFO---lower_case---Hate_classification.LOGGERS.logging---error applying the lowercase transformation - Error: "None of [Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,\n       ...\n       25286, 25287, 25288, 25289, 25290, 25291, 25292, 25294, 25295, 25296],\n      dtype='int64', length=24783)] are in the [columns]" has occurred in module: KeyError, line: 64, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,305---INFO---lower_case---Hate_classification.LOGGERS.logging---error applying the lowercase transformation - Error: "None of [Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,\n       ...\n       25286, 25287, 25288, 25289, 25290, 25291, 25292, 25294, 25295, 25296],\n      dtype='int64', length=24783)] are in the [columns]" has occurred in module: KeyError, line: 64, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,307---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 74, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,307---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 74, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,307---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 74, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,307---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 74, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,307---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 74, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,309---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 53, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,309---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 53, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,309---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 53, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,309---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 53, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 19:43:20,309---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: 'Logger' object is not callable has occurred in module: TypeError, line: 53, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,310---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---error occured while perfoming normalization data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 27, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,310---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---error occured while perfoming normalization data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 27, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,310---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---error occured while perfoming normalization data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 27, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,310---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---error occured while perfoming normalization data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 27, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 19:43:20,310---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---error occured while perfoming normalization data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 27, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
