ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 20:50:14,730---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---Initializing  data ingestion pipeline steps
data_ingestion.py----data_ingestion---2024-09-11 20:50:14,730---INFO---ingest_data---Hate_classification.LOGGERS.logging---initialized Reading CSV from { self.path} 
data_ingestion.py----data_ingestion---2024-09-11 20:50:14,730---INFO---ingest_data---Hate_classification.LOGGERS.logging---initialized Reading CSV from { self.path} 
ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 20:50:14,800---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---successfully finished data ingestion pipeline steps
ingestion_pipeline_steps.py----ingestion_pipeline_steps---2024-09-11 20:50:14,800---INFO---data_ingestion_pipeline---Hate_classification.LOGGERS.logging---successfully finished data ingestion pipeline steps
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,828---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,828---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,828---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Initializing data processing pipeline 
data_processing.py----data_processing---2024-09-11 20:50:14,829---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 20:50:14,829---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 20:50:14,829---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 20:50:14,829---INFO---preprocess_data---Hate_classification.LOGGERS.logging---initializing the dropping of the columns
data_processing.py----data_processing---2024-09-11 20:50:14,830---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 20:50:14,830---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 20:50:14,830---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 20:50:14,830---INFO---preprocess_data---Hate_classification.LOGGERS.logging---Columns available in DataFrame: ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither', 'class', 'tweet']
data_processing.py----data_processing---2024-09-11 20:50:14,832---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 20:50:14,832---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 20:50:14,832---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing.py----data_processing---2024-09-11 20:50:14,832---INFO---preprocess_data---Hate_classification.LOGGERS.logging---successfully dropped the columns
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,839---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,839---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,839---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,839---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---dropped columns successfully
data_processing.py----data_processing---2024-09-11 20:50:14,861---INFO---lower_case---Hate_classification.LOGGERS.logging---Successfully applied the lowercase transformation to the column: tweet
data_processing.py----data_processing---2024-09-11 20:50:14,861---INFO---lower_case---Hate_classification.LOGGERS.logging---Successfully applied the lowercase transformation to the column: tweet
data_processing.py----data_processing---2024-09-11 20:50:14,861---INFO---lower_case---Hate_classification.LOGGERS.logging---Successfully applied the lowercase transformation to the column: tweet
data_processing.py----data_processing---2024-09-11 20:50:14,861---INFO---lower_case---Hate_classification.LOGGERS.logging---Successfully applied the lowercase transformation to the column: tweet
data_processing.py----data_processing---2024-09-11 20:50:14,861---INFO---lower_case---Hate_classification.LOGGERS.logging---Successfully applied the lowercase transformation to the column: tweet
data_processing.py----data_processing---2024-09-11 20:50:14,871---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---started the drop_punctuations
data_processing.py----data_processing---2024-09-11 20:50:14,871---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---started the drop_punctuations
data_processing.py----data_processing---2024-09-11 20:50:14,871---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---started the drop_punctuations
data_processing.py----data_processing---2024-09-11 20:50:14,871---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---started the drop_punctuations
data_processing.py----data_processing---2024-09-11 20:50:14,871---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---started the drop_punctuations
data_processing.py----data_processing---2024-09-11 20:50:14,872---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: str.replace() takes no keyword arguments has occurred in module: TypeError, line: 88, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,872---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: str.replace() takes no keyword arguments has occurred in module: TypeError, line: 88, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,872---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: str.replace() takes no keyword arguments has occurred in module: TypeError, line: 88, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,872---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: str.replace() takes no keyword arguments has occurred in module: TypeError, line: 88, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,872---INFO---drop_punctuations---Hate_classification.LOGGERS.logging---error dropping punctuations and urls - Error: str.replace() takes no keyword arguments has occurred in module: TypeError, line: 88, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,878---INFO---drop_stopwords---Hate_classification.LOGGERS.logging---drop_stopwords has been initialized
data_processing.py----data_processing---2024-09-11 20:50:14,878---INFO---drop_stopwords---Hate_classification.LOGGERS.logging---drop_stopwords has been initialized
data_processing.py----data_processing---2024-09-11 20:50:14,878---INFO---drop_stopwords---Hate_classification.LOGGERS.logging---drop_stopwords has been initialized
data_processing.py----data_processing---2024-09-11 20:50:14,878---INFO---drop_stopwords---Hate_classification.LOGGERS.logging---drop_stopwords has been initialized
data_processing.py----data_processing---2024-09-11 20:50:14,878---INFO---drop_stopwords---Hate_classification.LOGGERS.logging---drop_stopwords has been initialized
data_processing.py----data_processing---2024-09-11 20:50:14,880---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,880---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,880---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,880---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,880---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,881---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,881---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,881---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,881---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,881---ERROR---remove_stopwords---Hate_classification.LOGGERS.logging---could not remove the stop words from the dataframe  - Error: cannot access local variable 'e' where it is not associated with a value has occurred in module: UnboundLocalError, line: 115, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,883---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: Columns must be same length as key has occurred in module: ValueError, line: 54, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,883---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: Columns must be same length as key has occurred in module: ValueError, line: 54, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,883---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: Columns must be same length as key has occurred in module: ValueError, line: 54, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,883---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: Columns must be same length as key has occurred in module: ValueError, line: 54, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing.py----data_processing---2024-09-11 20:50:14,883---ERROR---preprocess_data---Hate_classification.LOGGERS.logging---there was an error while perfoming the normalization steps - Error: Columns must be same length as key has occurred in module: ValueError, line: 54, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\COMPONENTS\data_processing.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Successfully done the normalization
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Successfully done the normalization
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Successfully done the normalization
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Successfully done the normalization
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---INFO---data_processing_pipeline---Hate_classification.LOGGERS.logging---Successfully done the normalization
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---Error occurred while processing data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 34, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---Error occurred while processing data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 34, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---Error occurred while processing data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 34, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---Error occurred while processing data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 34, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
data_processing_pipeline.py----data_processing_pipeline---2024-09-11 20:50:14,885---ERROR---data_processing_pipeline---Hate_classification.LOGGERS.logging---Error occurred while processing data - Error: 'NoneType' object has no attribute 'head' has occurred in module: AttributeError, line: 34, file: C:\Users\User\Desktop\nlp_text_class\Hate_classification\PIPELINE\data_processing_pipeline.py
